# Copyright Fauna, Inc.
# SPDX-License-Identifier: MIT-0

name = "vue-fauna-edge-api-spa"
type = "webpack"
account_id = ""
route = ''
zone_id = ''
workers_dev = true

[site]
# The directory containing your static assets (output of your build)
bucket = "../../../dist"

# The location of the worker entry-point. Leave untouched.
entry-point = "workers-site"